# Generated by Django 4.1.1 on 2022-09-08 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('host', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('price', models.DecimalField(decimal_places=8, max_digits=10)),
                ('event_image_url', models.ImageField(null=True, upload_to='eventImage')),
                ('activity_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_activity_levels', to='mindfuljourneyapi.activitylevel')),
            ],
        ),
        migrations.CreateModel(
            name='Meditator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('profile_image_url', models.ImageField(null=True, upload_to='profileImage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('created_on', models.DateField()),
                ('post_image_url', models.ImageField(null=True, upload_to='postImage')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=20)),
                ('meditator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to='mindfuljourneyapi.meditator')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to='mindfuljourneyapi.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250)),
                ('created_on', models.DateField()),
                ('meditator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='mindfuljourneyapi.meditator')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='mindfuljourneyapi.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='mindfuljourneyapi.postcategory'),
        ),
        migrations.AddField(
            model_name='post',
            name='meditator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='mindfuljourneyapi.meditator'),
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tags', to='mindfuljourneyapi.event')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tags', to='mindfuljourneyapi.tag')),
            ],
        ),
        migrations.CreateModel(
            name='EventReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reactions', to='mindfuljourneyapi.event')),
                ('meditator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reactions', to='mindfuljourneyapi.meditator')),
            ],
        ),
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250)),
                ('created_on', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_comments', to='mindfuljourneyapi.event')),
                ('meditator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_comments', to='mindfuljourneyapi.meditator')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindfuljourneyapi.event')),
                ('meditator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindfuljourneyapi.meditator')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='mediator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindfuljourneyapi.meditator'),
        ),
    ]
