# Generated by Django 4.1.1 on 2022-09-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindfuljourneyapi', '0005_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default='2022-01-01'),
        ),
    ]
